name: "JFrog Integration Example"
on: push

jobs:
  build:
     runs-on: ubuntu-latest
       
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: ${{ vars.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
           
       - name: uv test
         run: |
           curl -LsSf https://astral.sh/uv/install.sh | sh
           uv auth login $JF_URL --username tomas.miklusicak@cloudops.sk --password $JF_ACCESS_TOKEN
           uv init abc
           cd abc
           uv add yamllint
           
    
